/** require.js config
 *
 * Note : for the optimizer to work correctly :
 *  - no "code"
 *  - no extra stuff
 */

requirejs.config({

	// base URL from which component files will be searched
	// NOTE 1 : non-rsrc url below may not be affected by baseUrl
	// NOTE 2 : relative baseUrl base refers to *the calling html* ! (may need to be overridden)
	baseUrl: '../..',

	// http://requirejs.org/docs/api.html#config-enforceDefine
	enforceDefine: false,

	map: {
		'*': {
			'css': 'bower_components/require-css/css',
			// a require.js extension to be able to load dust.js templates easily
			'rdust': 'bower_components/require-dust/rdust',
			// a require.js extension to be able to wait for the DOM to be ready
			'domReady': 'bower_components/requirejs-domready/domReady',
			// transparently replace underscore with lodash
			'underscore' : 'lodash'
		}
	},

	/////////////////////
	// multi-files modules
	packages: [
	],

	/////////////////////
	paths: {

		/////// shim plugins
		'angular'                  : 'bower_components/angular/angular',
		'angular-bootstrap'        : 'bower_components/angular-bootstrap/ui-bootstrap-tpls',
		'angular-strap'            : 'bower_components/angular-strap/dist/angular-strap.tpl',
		'angular-strap-base'       : 'bower_components/angular-strap/dist/angular-strap',
		'angular-ui-router'        : 'bower_components/angular-ui-router/release/angular-ui-router',
		'angular-ui-router-extras' : 'bower_components/ui-router-extras/release/ct-ui-router-extras',
		'angular-rx'               : 'bower_components/angular-rx/dist/rx.angular',
		'bootstrap'                : 'bower_components/bootstrap/dist/js/bootstrap',
		// dust-full : this plugin MUST be aliased 'dust' for rdust to work properly, see 'dust' below
		'dust'                     : 'bower_components/dustjs-linkedin/dist/dust-full',
		'dust-helpers'             : 'bower_components/dustjs-linkedin-helpers/dist/dust-helpers',
		'eventemitter2'            : 'bower_components/eventemitter2/lib/eventemitter2',
		'extended-exceptions'      : 'bower_components/extended-exceptions.js/extended_exceptions',
		'humanize-duration'        : 'bower_components/humanize-duration/humanize-duration',
		'javascript-state-machine' : 'bower_components/javascript-state-machine/state-machine',
		'jquery'                   : 'bower_components/jquery/dist/jquery',
		'lodash'                   : 'bower_components/lodash/lodash',
		'moment'                   : 'bower_components/moment/min/moment-with-locales',
		'onepage-scroll'           : 'bower_components/onepage-scroll/jquery.onepage-scroll',
		'primus'                   : 'client/common/other_components/primus-client-autogenerated/primus',
		'rx'                       : 'bower_components/rxjs/dist/rx.all',
		'screenfull'               : 'bower_components/screenfull/dist/screenfull',
		// require.js extensions (plugin) to be able to load any kind of text with require.js
		'text'                     : 'bower_components/requirejs-text/text',
		'underscore.string'        : 'bower_components/underscore.string/dist/underscore.string',
		//'underscore'  -> replaced by lodash, see "map" section above.
	},


	/////////////////////
	shim: {
		/////// require.js extensions
		'rdust' : {
			deps: [ 'dust-helpers' ]
		},

		/////// AMD plugins

		/////// shim plugins
		'angular': {
			deps: [ 'jquery' ], // angular has its own jQlite, but will use main jQuery if already available
			exports: 'angular'
		},
		'angular-bootstrap': {
			deps: [
				'angular',
				//'bootstrap', XXX No ! angular-bootstrap replaces bootstrap js, it only needs bootstrap css
				'css!bower_components/bootstrap-css/css/bootstrap'
			]
		},
		// 2 stage due to double file :
		'angular-strap': {
			deps: [ 'angular-strap-base' ]
		},
		'angular-strap-base': {
			deps: [
				'angular',
				// angular-strap replaces bootstrap js, it only needs bootstrap css
				'css!bower_components/bootstrap-css/css/bootstrap'
			]
		},
		'angular-ui-router': {
			deps: [ 'angular' ]
		},
		'angular-ui-router-extras': {
			deps: [ 'angular-ui-router' ]
		},
		'angular-rx': {
			deps: [ 'angular' ]
		},
		'bootstrap': {
			deps: [
				// bootstrap js needs jQuery http://getbootstrap.com/getting-started/#whats-included
				'jquery',
				'css!bower_components/bootstrap/dist/css/bootstrap'
			]
		},
		'bootstrap-with-cyborg-theme': {
			deps: [
				// bootstrap js needs jQuery http://getbootstrap.com/getting-started/#whats-included
				'jquery',
				'css!client/common/other_components/bootswatch/cyborg/cyborg-bootstrap.min'
			]
		},
		'dust': {
			// no deps
			exports: 'dust'
		},
		'dust-helpers': {
			deps: [ 'dust' ],
			exports: 'dust'
		},
		'famous': {
			deps: [
				'famous-global',
				'css!bower_components/famous/dist/famous'
			]
		},
		'famous-angular': {
			deps: [
				'famous-global',
				'angular',
				'css!bower_components/famous-angular/dist/famous-angular'
			],
			init: function (famous) {
				// famous-angular needs famous as a global var...
				window.famous = famous;
			}
		},
		'famous-global': {
			//exports: 'famous'
		},
		'intl-messageformat': {
			exports: 'IntlMessageFormat'
		},
		'intl-relativeformat': {
			exports: 'IntlRelativeFormat'
		},
		'javascript-state-machine' : {
			// no deps
			exports: 'StateMachine'
		},
		'jquery.poptrox': {
			deps: [ 'jquery' ]
		},
		'lodash': {
			exports: '_'
		},
		'messenger': {
			deps: [
				'jquery',
				'css!bower_components/messenger/build/css/messenger'
			]
		},
		'messenger-theme-future': {
			deps: [
				'messenger',
				'css!bower_components/messenger/build/css/messenger-theme-future'
			],
			exports: 'Messenger'
		},
		'screenfull': {
			exports: 'screenfull'
		},
		'spin': {
			exports: 'Spinner'
		}
	},

	/////////////////////
	config: {
		// http://requirejs.org/docs/api.html#i18n
		i18n: {
			// can't resolve locale here : this file can't have logic, to be able to be minified by r.js
			// and we need some logic (ex. load selected locale from local storage)
		}
	},

	/////////////////////
	// dependencies to load as soon as require.js defines require
	//deps: [ ]
});
